### ISSUE TITLE
[CAR shop] Buying menu disappear

### ISSUE THREAD

**Issue by Nice-ToSeeYou** [HumanTree92/esx_advancedvehicleshop#10]
When I change the vehicle to see other options inside the shop, the buying menu disappear and I cannot enter, leave, start, buy a car anymore. My ped is invisible and I cannot access any menu anymore. But the new car is spawned.

**Comment by dutchplayers** [comment]
We have the same issue :(

**Comment by HumanTree92** [comment]
Any errors in server logs or client logs. I have fully tested this and have not had a single problem. Also what hosting services are u using.

**Comment by Nice-ToSeeYou** [comment]
No errors anywhere (that the weirdest part).
See following pictures, do not pay attention to the local FR not existing I am still translating the thing and it was already happening with the English text.
![Capture1](https://user-images.githubusercontent.com/38940602/78193778-981c1c80-747b-11ea-80ff-e0ca97c9692c.PNG)
![Capture2](https://user-images.githubusercontent.com/38940602/78193779-98b4b300-747b-11ea-8f86-b72c56ff131c.PNG)

**Comment by HumanTree92** [comment]
R u using the default esx_menu

**Comment by HumanTree92** [comment]
Also try to use the default esx_vehicleshop and see if that works. If that works & then this doesn't let me know. But there isn't much to go on b/c i have been using this in my test server with over 5 people testing and we have not had a single problem with this.

**Comment by Nice-ToSeeYou** [comment]
So esx_vehicleshop is working fine :( 
I am using the default esx_menu just changed how it looks

I made another few tests, and all the other vehicle shop are working (boat/truck/plane) just the car Oo

**Comment by HumanTree92** [comment]
Ok so i fixed a few things wrong with the sql. Make sure you have the correct stuff in the sql

**Comment by Nice-ToSeeYou** [comment]
Found it!
I am just dumb... I did not see that esx_policejob had still the dependency for esx_vehicleshop inside the fxmanifest. Deleted it and now it is working fine!
Thanks for the help!

**Comment by HumanTree92** [comment]
Ah yes. That is noted in the readme

**Comment by dutchplayers** [comment]
I have this issue still. 

No errors at all :( Checked depedencies

**Comment by SpiderAang** [comment]
> I have this issue still.
> 
> No errors at all :( Checked depedencies

Check this 
1)
![image](https://user-images.githubusercontent.com/63131372/78416722-9f862600-7633-11ea-8198-70082f65bc01.png)
2)
![image](https://user-images.githubusercontent.com/63131372/78416728-b0cf3280-7633-11ea-9e68-0704f3a20f18.png)
3)
![image](https://user-images.githubusercontent.com/63131372/78416740-c5abc600-7633-11ea-87d4-1a6d1b457053.png)
4)Just Delete it
I had the same problem and just now I found what was wrong

**Comment by HumanTree92** [comment]
esx_boat, esx_truckshop, & esx_aircraftshop are no longer supported by me anymore as they are pointless. This script alone makes things 10x easier plus allows players easily add more shops to their liking. I forgot to add the note about esx_ambulancejob but will do that ASAP.

**Comment by dutchplayers** [comment]
I did check all my resource files. 

I do not use esx_boat or esx_aircraftshop anymore.

I cannot open the menu's

**Comment by dutchplayers** [comment]
client/main.lua:457: bad argument #1 to 'insert' (table expected, got nill)

I did a fresh database

**Comment by dutchplayers** [comment]
I think your vehicle list is not good
